{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c049ef98-5250-4520-8724-0d4e70679a80",
   "metadata": {},
   "outputs": [],
   "source": [
    "pip install openmeteo-requests\n",
    "pip install requests-cache retry-requests numpy pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f9543f1d-885a-4418-a2ae-2a073062cd36",
   "metadata": {},
   "outputs": [],
   "source": [
    "import openmeteo_requests\n",
    "\n",
    "import pandas as pd\n",
    "import requests_cache\n",
    "from retry_requests import retry\n",
    "\n",
    "# Setup the Open-Meteo API client with cache and retry on error\n",
    "cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)\n",
    "retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)\n",
    "openmeteo = openmeteo_requests.Client(session = retry_session)\n",
    "\n",
    "# Make sure all required weather variables are listed here\n",
    "# The order of variables in hourly or daily is important to assign them correctly below\n",
    "url = \"https://air-quality-api.open-meteo.com/v1/air-quality\"\n",
    "params = {\n",
    "\t\"latitude\": [38.2542, 20.8893, 25.9017, 44.0521, 45.6797, 42.8666, 35.3733],\n",
    "\t\"longitude\": [-85.7594, -156.4729, -97.4975, -123.0867, -111.0386, -106.3131, -119.0187],\n",
    "\t\"hourly\": [\"pm10\", \"pm2_5\", \"carbon_dioxide\", \"nitrogen_dioxide\", \"sulphur_dioxide\", \"ozone\", \"aerosol_optical_depth\", \"uv_index\", \"dust\", \"uv_index_clear_sky\"],\n",
    "\t\"current\": [\"us_aqi\", \"pm10\", \"pm2_5\", \"carbon_monoxide\", \"nitrogen_dioxide\", \"sulphur_dioxide\", \"ozone\", \"aerosol_optical_depth\", \"dust\", \"uv_index\", \"uv_index_clear_sky\"],\n",
    "\t\"forecast_days\": 7,\n",
    "}\n",
    "responses = openmeteo.weather_api(url, params = params)\n",
    "\n",
    "# Process 7 locations\n",
    "for response in responses:\n",
    "\tprint(f\"\\nCoordinates: {response.Latitude()}°N {response.Longitude()}°E\")\n",
    "\tprint(f\"Elevation: {response.Elevation()} m asl\")\n",
    "\tprint(f\"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s\")\n",
    "\t\n",
    "\t# Process current data. The order of variables needs to be the same as requested.\n",
    "\tcurrent = response.Current()\n",
    "\tcurrent_us_aqi = current.Variables(0).Value()\n",
    "\tcurrent_pm10 = current.Variables(1).Value()\n",
    "\tcurrent_pm2_5 = current.Variables(2).Value()\n",
    "\tcurrent_carbon_monoxide = current.Variables(3).Value()\n",
    "\tcurrent_nitrogen_dioxide = current.Variables(4).Value()\n",
    "\tcurrent_sulphur_dioxide = current.Variables(5).Value()\n",
    "\tcurrent_ozone = current.Variables(6).Value()\n",
    "\tcurrent_aerosol_optical_depth = current.Variables(7).Value()\n",
    "\tcurrent_dust = current.Variables(8).Value()\n",
    "\tcurrent_uv_index = current.Variables(9).Value()\n",
    "\tcurrent_uv_index_clear_sky = current.Variables(10).Value()\n",
    "\t\n",
    "\tprint(f\"\\nCurrent time: {current.Time()}\")\n",
    "\tprint(f\"Current us_aqi: {current_us_aqi}\")\n",
    "\tprint(f\"Current pm10: {current_pm10}\")\n",
    "\tprint(f\"Current pm2_5: {current_pm2_5}\")\n",
    "\tprint(f\"Current carbon_monoxide: {current_carbon_monoxide}\")\n",
    "\tprint(f\"Current nitrogen_dioxide: {current_nitrogen_dioxide}\")\n",
    "\tprint(f\"Current sulphur_dioxide: {current_sulphur_dioxide}\")\n",
    "\tprint(f\"Current ozone: {current_ozone}\")\n",
    "\tprint(f\"Current aerosol_optical_depth: {current_aerosol_optical_depth}\")\n",
    "\tprint(f\"Current dust: {current_dust}\")\n",
    "\tprint(f\"Current uv_index: {current_uv_index}\")\n",
    "\tprint(f\"Current uv_index_clear_sky: {current_uv_index_clear_sky}\")\n",
    "\t\n",
    "\t# Process hourly data. The order of variables needs to be the same as requested.\n",
    "\thourly = response.Hourly()\n",
    "\thourly_pm10 = hourly.Variables(0).ValuesAsNumpy()\n",
    "\thourly_pm2_5 = hourly.Variables(1).ValuesAsNumpy()\n",
    "\thourly_carbon_dioxide = hourly.Variables(2).ValuesAsNumpy()\n",
    "\thourly_nitrogen_dioxide = hourly.Variables(3).ValuesAsNumpy()\n",
    "\thourly_sulphur_dioxide = hourly.Variables(4).ValuesAsNumpy()\n",
    "\thourly_ozone = hourly.Variables(5).ValuesAsNumpy()\n",
    "\thourly_aerosol_optical_depth = hourly.Variables(6).ValuesAsNumpy()\n",
    "\thourly_uv_index = hourly.Variables(7).ValuesAsNumpy()\n",
    "\thourly_dust = hourly.Variables(8).ValuesAsNumpy()\n",
    "\thourly_uv_index_clear_sky = hourly.Variables(9).ValuesAsNumpy()\n",
    "\t\n",
    "\thourly_data = {\n",
    "\t\t\"date\": pd.date_range(\n",
    "\t\t\tstart = pd.to_datetime(hourly.Time(), unit = \"s\", utc = True),\n",
    "\t\t\tend =  pd.to_datetime(hourly.TimeEnd(), unit = \"s\", utc = True),\n",
    "\t\t\tfreq = pd.Timedelta(seconds = hourly.Interval()),\n",
    "\t\t\tinclusive = \"left\"\n",
    "\t\t)\n",
    "\t}\n",
    "\t\n",
    "\thourly_data[\"pm10\"] = hourly_pm10\n",
    "\thourly_data[\"pm2_5\"] = hourly_pm2_5\n",
    "\thourly_data[\"carbon_dioxide\"] = hourly_carbon_dioxide\n",
    "\thourly_data[\"nitrogen_dioxide\"] = hourly_nitrogen_dioxide\n",
    "\thourly_data[\"sulphur_dioxide\"] = hourly_sulphur_dioxide\n",
    "\thourly_data[\"ozone\"] = hourly_ozone\n",
    "\thourly_data[\"aerosol_optical_depth\"] = hourly_aerosol_optical_depth\n",
    "\thourly_data[\"uv_index\"] = hourly_uv_index\n",
    "\thourly_data[\"dust\"] = hourly_dust\n",
    "\thourly_data[\"uv_index_clear_sky\"] = hourly_uv_index_clear_sky\n",
    "\t\n",
    "\thourly_dataframe = pd.DataFrame(data = hourly_data)\n",
    "\tprint(\"\\nHourly data\\n\", hourly_dataframe)\n",
    "\t"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
