{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "cb6d14f8-53ee-407e-8e0e-1ee6a89d7711",
   "metadata": {
    "editable": true,
    "slideshow": {
     "slide_type": ""
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "import os\n",
    "os.environ[\"DB_HOST\"]     = \"db.iarjtljgdrawvdbcnsgi.supabase.co\"  # your host\n",
    "os.environ[\"DB_NAME\"]     = \"postgres\"                      # Supabase default\n",
    "os.environ[\"DB_USER\"]     = \"postgres\"                      # Supabase default\n",
    "os.environ[\"DB_PASSWORD\"] = \"ShgEOjWl1YZgJGFs\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "6afcdffb-9df1-463c-a294-5d51003bbd15",
   "metadata": {
    "editable": true,
    "slideshow": {
     "slide_type": ""
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-06-04 00:15:01,319 [INFO] ============================================================\n",
      "2026-06-04 00:15:01,319 [INFO] Air Quality Pipeline — START\n",
      "2026-06-04 00:15:01,319 [INFO] ============================================================\n",
      "2026-06-04 00:15:01,320 [INFO] Extracting data from Open-Meteo API …\n",
      "2026-06-04 00:15:01,324 [INFO]   → 7 location responses received from API\n",
      "2026-06-04 00:15:01,331 [INFO]   → 1,176 hourly rows across 7 locations\n",
      "2026-06-04 00:15:01,331 [INFO] Cleaning and normalising …\n",
      "2026-06-04 00:15:01,358 [INFO]   → 8,232 remaining nulls after interpolation\n",
      "2026-06-04 00:15:01,359 [INFO] Transforming and deriving metrics …\n",
      "2026-06-04 00:15:01,367 [INFO]   → Derived columns added\n",
      "2026-06-04 00:15:01,367 [INFO] Running data validation …\n",
      "2026-06-04 00:15:01,368 [INFO]   [QA PASS] null_time\n",
      "2026-06-04 00:15:01,369 [INFO]   [QA PASS] duplicate_location_time\n",
      "2026-06-04 00:15:01,369 [INFO]   [QA PASS] unknown_location_id\n",
      "2026-06-04 00:15:01,370 [INFO]   [QA PASS] aqi_out_of_range\n",
      "2026-06-04 00:15:01,370 [INFO]   [QA PASS] uv_out_of_range\n",
      "2026-06-04 00:15:01,371 [INFO]   [QA PASS] negative_concentration\n",
      "2026-06-04 00:15:01,371 [INFO]   [QA PASS] negative_concentration\n",
      "2026-06-04 00:15:01,372 [INFO]   [QA PASS] negative_concentration\n",
      "2026-06-04 00:15:01,372 [INFO]   [QA PASS] negative_concentration\n",
      "2026-06-04 00:15:01,373 [WARNING]   [QA FAIL] high_null_rate | column: pm10 | 420 rows | 35.7% missing\n",
      "2026-06-04 00:15:01,373 [WARNING]   [QA FAIL] high_null_rate | column: pm2_5 | 420 rows | 35.7% missing\n",
      "2026-06-04 00:15:01,374 [WARNING]   [QA FAIL] high_null_rate | column: carbon_monoxide | 420 rows | 35.7% missing\n",
      "2026-06-04 00:15:01,374 [WARNING]   [QA FAIL] high_null_rate | column: carbon_dioxide | 490 rows | 41.7% missing\n",
      "2026-06-04 00:15:01,375 [WARNING]   [QA FAIL] high_null_rate | column: nitrogen_dioxide | 420 rows | 35.7% missing\n",
      "2026-06-04 00:15:01,375 [WARNING]   [QA FAIL] high_null_rate | column: sulphur_dioxide | 420 rows | 35.7% missing\n",
      "2026-06-04 00:15:01,376 [WARNING]   [QA FAIL] high_null_rate | column: ozone | 420 rows | 35.7% missing\n",
      "2026-06-04 00:15:01,376 [WARNING]   [QA FAIL] high_null_rate | column: methane | 490 rows | 41.7% missing\n",
      "2026-06-04 00:15:01,376 [WARNING]   [QA FAIL] high_null_rate | column: uv_index_clear_sky | 441 rows | 37.5% missing\n",
      "2026-06-04 00:15:01,377 [WARNING]   [QA FAIL] high_null_rate | column: uv_index | 420 rows | 35.7% missing\n",
      "2026-06-04 00:15:01,377 [WARNING]   [QA FAIL] high_null_rate | column: dust | 420 rows | 35.7% missing\n",
      "2026-06-04 00:15:01,377 [WARNING]   [QA FAIL] high_null_rate | column: aerosol_optical_depth | 420 rows | 35.7% missing\n",
      "2026-06-04 00:15:01,378 [WARNING]   [QA FAIL] high_null_rate | column: us_aqi | 413 rows | 35.1% missing\n",
      "2026-06-04 00:15:01,378 [WARNING]   [QA FAIL] high_null_rate | column: us_aqi_pm2_5 | 434 rows | 36.9% missing\n",
      "2026-06-04 00:15:01,379 [WARNING]   [QA FAIL] high_null_rate | column: us_aqi_pm10 | 434 rows | 36.9% missing\n",
      "2026-06-04 00:15:01,380 [WARNING]   [QA FAIL] high_null_rate | column: us_aqi_nitrogen_dioxide | 441 rows | 37.5% missing\n",
      "2026-06-04 00:15:01,381 [WARNING]   [QA FAIL] high_null_rate | column: us_aqi_carbon_monoxide | 434 rows | 36.9% missing\n",
      "2026-06-04 00:15:01,381 [WARNING]   [QA FAIL] high_null_rate | column: us_aqi_ozone | 434 rows | 36.9% missing\n",
      "2026-06-04 00:15:01,381 [WARNING]   [QA FAIL] high_null_rate | column: us_aqi_sulphur_dioxide | 441 rows | 37.5% missing\n",
      "2026-06-04 00:15:01,382 [WARNING]   [QA FAIL] high_null_rate | column: aqi_category | 413 rows | 35.1% missing\n",
      "2026-06-04 00:15:01,383 [WARNING]   [QA FAIL] high_null_rate | column: dominant_pollutant | 434 rows | 36.9% missing\n",
      "2026-06-04 00:15:01,383 [WARNING]   [QA FAIL] high_null_rate | column: pm_ratio | 420 rows | 35.7% missing\n",
      "2026-06-04 00:15:01,384 [WARNING]   [QA FAIL] high_null_rate | column: uv_cloud_attenuation_pct | 773 rows | 65.7% missing\n",
      "2026-06-04 00:15:01,389 [INFO]   → QA complete: 9 checks passed, 23 with issues\n",
      "2026-06-04 00:15:01,585 [INFO]   → PostgreSQL engine created: postgres@db.iarjtljgdrawvdbcnsgi.supabase.co:5432/postgres\n",
      "2026-06-04 00:15:01,585 [INFO] Loading to PostgreSQL (incremental append with deduplication) …\n",
      "2026-06-04 00:15:02,799 [INFO]   → locations: upserted 7 rows\n",
      "2026-06-04 00:15:03,409 [INFO]   → readings: 1176 rows written\n",
      "2026-06-04 00:15:03,967 [INFO]   → particulates: 1176 rows written\n",
      "2026-06-04 00:15:04,532 [INFO]   → gaseous_pollutants: 1176 rows written\n",
      "2026-06-04 00:15:05,043 [INFO]   → greenhouse_gases: 1176 rows written\n",
      "2026-06-04 00:15:05,593 [INFO]   → atmospheric: 1176 rows written\n",
      "2026-06-04 00:15:05,792 [INFO]   → Row count check: 1344 rows in DB readings table\n",
      "2026-06-04 00:15:05,933 [INFO]   → Pipeline run recorded in pipeline_runs audit table\n",
      "2026-06-04 00:15:05,934 [INFO] Exporting CSVs to output …\n",
      "2026-06-04 00:15:05,965 [INFO]   → CSVs written: locations.csv, readings_clean.csv, qa_report.csv\n",
      "2026-06-04 00:15:05,965 [INFO] Building analytics-ready datasets …\n",
      "2026-06-04 00:15:05,994 [INFO]   A) Daily summary: 56 rows → analytics_daily_summary.csv\n",
      "2026-06-04 00:15:06,005 [INFO]   B) AQI wide pivot: (109, 8) → analytics_aqi_wide.csv\n",
      "2026-06-04 00:15:06,013 [INFO]   C) WHO exceedance log: 200 rows → analytics_who_exceedances.csv\n",
      "2026-06-04 00:15:06,014 [INFO] Analytics datasets ready.\n",
      "2026-06-04 00:15:06,014 [INFO] ============================================================\n",
      "2026-06-04 00:15:06,015 [INFO] Pipeline complete.\n",
      "2026-06-04 00:15:06,015 [INFO] ============================================================\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Sample enriched data:\n",
      " location_id                      time    us_aqi aqi_category dominant_pollutant  pm_ratio\n",
      "           0 2026-06-04 04:00:00+00:00 42.961502         Good              Ozone     0.899\n",
      "           0 2026-06-04 05:00:00+00:00 39.424862         Good              Ozone     0.897\n",
      "           0 2026-06-04 06:00:00+00:00 36.004173         Good              Ozone     0.899\n",
      "           0 2026-06-04 07:00:00+00:00 32.873375         Good              Ozone     0.892\n",
      "           0 2026-06-04 08:00:00+00:00 30.090443         Good              Ozone     0.895\n",
      "           0 2026-06-04 09:00:00+00:00 27.539427         Good              Ozone     0.904\n",
      "           0 2026-06-04 10:00:00+00:00 25.394249         Good              Ozone     0.913\n",
      "           0 2026-06-04 11:00:00+00:00 25.486109         Good              PM2.5     0.922\n",
      "           0 2026-06-04 12:00:00+00:00 26.545137         Good              PM2.5     0.928\n",
      "           0 2026-06-04 13:00:00+00:00 27.256943         Good              PM2.5     0.919\n",
      "\n",
      "QA Report:\n",
      "                  check                   column  failed_rows            detail status\n",
      "              null_time                     time            0                     PASS\n",
      "duplicate_location_time         location_id+time            0                     PASS\n",
      "    unknown_location_id              location_id            0                     PASS\n",
      "       aqi_out_of_range                   us_aqi            0 valid range 0–500   PASS\n",
      "        uv_out_of_range                 uv_index            0  valid range 0–20   PASS\n",
      " negative_concentration                    pm2_5            0                     PASS\n",
      " negative_concentration                     pm10            0                     PASS\n",
      " negative_concentration                    ozone            0                     PASS\n",
      " negative_concentration          carbon_monoxide            0                     PASS\n",
      "         high_null_rate                     pm10          420     35.7% missing   FAIL\n",
      "         high_null_rate                    pm2_5          420     35.7% missing   FAIL\n",
      "         high_null_rate          carbon_monoxide          420     35.7% missing   FAIL\n",
      "         high_null_rate           carbon_dioxide          490     41.7% missing   FAIL\n",
      "         high_null_rate         nitrogen_dioxide          420     35.7% missing   FAIL\n",
      "         high_null_rate          sulphur_dioxide          420     35.7% missing   FAIL\n",
      "         high_null_rate                    ozone          420     35.7% missing   FAIL\n",
      "         high_null_rate                  methane          490     41.7% missing   FAIL\n",
      "         high_null_rate       uv_index_clear_sky          441     37.5% missing   FAIL\n",
      "         high_null_rate                 uv_index          420     35.7% missing   FAIL\n",
      "         high_null_rate                     dust          420     35.7% missing   FAIL\n",
      "         high_null_rate    aerosol_optical_depth          420     35.7% missing   FAIL\n",
      "         high_null_rate                   us_aqi          413     35.1% missing   FAIL\n",
      "         high_null_rate             us_aqi_pm2_5          434     36.9% missing   FAIL\n",
      "         high_null_rate              us_aqi_pm10          434     36.9% missing   FAIL\n",
      "         high_null_rate  us_aqi_nitrogen_dioxide          441     37.5% missing   FAIL\n",
      "         high_null_rate   us_aqi_carbon_monoxide          434     36.9% missing   FAIL\n",
      "         high_null_rate             us_aqi_ozone          434     36.9% missing   FAIL\n",
      "         high_null_rate   us_aqi_sulphur_dioxide          441     37.5% missing   FAIL\n",
      "         high_null_rate             aqi_category          413     35.1% missing   FAIL\n",
      "         high_null_rate       dominant_pollutant          434     36.9% missing   FAIL\n",
      "         high_null_rate                 pm_ratio          420     35.7% missing   FAIL\n",
      "         high_null_rate uv_cloud_attenuation_pct          773     65.7% missing   FAIL\n"
     ]
    }
   ],
   "source": [
    "#Dependencies:\n",
    "   # pip install openmeteo-requests requests-cache retry-requests pandas sqlalchemy psycopg2-binary\n",
    "\n",
    "\n",
    "import os\n",
    "import logging\n",
    "import warnings\n",
    "from datetime import datetime, timezone\n",
    "from pathlib import Path\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Logging\n",
    "# ---------------------------------------------------------------------------\n",
    "logging.basicConfig(\n",
    "    level=logging.INFO,\n",
    "    format=\"%(asctime)s [%(levelname)s] %(message)s\",\n",
    "    handlers=[logging.StreamHandler()],\n",
    ")\n",
    "log = logging.getLogger(__name__)\n",
    "warnings.filterwarnings(\"ignore\", category=FutureWarning)\n",
    "\n",
    "\n",
    "# ===========================================================================\n",
    "# CONFIGURATION\n",
    "# ===========================================================================\n",
    "\n",
    "LOCATION_METADATA = {\n",
    "    0: {\"name\": \"Louisville, KY\",  \"state\": \"KY\", \"country\": \"US\"},\n",
    "    1: {\"name\": \"Bakersfield, CA\", \"state\": \"CA\", \"country\": \"US\"},\n",
    "    2: {\"name\": \"Brownsville, TX\", \"state\": \"TX\", \"country\": \"US\"},\n",
    "    3: {\"name\": \"Eugene, OR\",      \"state\": \"OR\", \"country\": \"US\"},\n",
    "    4: {\"name\": \"Bozeman, MT\",     \"state\": \"MT\", \"country\": \"US\"},\n",
    "    5: {\"name\": \"Casper, WY\",      \"state\": \"WY\", \"country\": \"US\"},\n",
    "    6: {\"name\": \"Kahului, HI\",     \"state\": \"HI\", \"country\": \"US\"},\n",
    "}\n",
    "\n",
    "API_URL = \"https://air-quality-api.open-meteo.com/v1/air-quality\"\n",
    "API_PARAMS = {\n",
    "    \"latitude\":  [38.2542, 35.3733, 25.9017, 44.0521, 45.6797, 42.8666, 20.8893],\n",
    "    \"longitude\": [-85.7594, -119.0187, -97.4975, -123.0867, -111.0386, -106.3131, -156.4729],\n",
    "    \"hourly\": [\n",
    "        \"pm10\", \"pm2_5\", \"carbon_monoxide\", \"carbon_dioxide\",\n",
    "        \"nitrogen_dioxide\", \"sulphur_dioxide\", \"ozone\", \"methane\",\n",
    "        \"uv_index_clear_sky\", \"uv_index\", \"dust\", \"aerosol_optical_depth\",\n",
    "        \"us_aqi\", \"us_aqi_pm2_5\", \"us_aqi_pm10\", \"us_aqi_nitrogen_dioxide\",\n",
    "        \"us_aqi_carbon_monoxide\", \"us_aqi_ozone\", \"us_aqi_sulphur_dioxide\",\n",
    "    ],\n",
    "    \"timezone\": \"America/New_York\",\n",
    "    \"forecast_days\": 7,\n",
    "}\n",
    "\n",
    "# WHO / EPA guideline thresholds (24-h means unless noted)\n",
    "THRESHOLDS = {\n",
    "    \"pm2_5\":            {\"who\": 15.0,  \"epa\": 35.0,   \"unit\": \"µg/m³\"},\n",
    "    \"pm10\":             {\"who\": 45.0,  \"epa\": 150.0,  \"unit\": \"µg/m³\"},\n",
    "    \"ozone\":            {\"who\": 100.0, \"epa\": 140.0,  \"unit\": \"µg/m³\"},  # 8-h mean\n",
    "    \"nitrogen_dioxide\": {\"who\": 25.0,  \"epa\": 100.0,  \"unit\": \"µg/m³\"},\n",
    "    \"sulphur_dioxide\":  {\"who\": 40.0,  \"epa\": 196.0,  \"unit\": \"µg/m³\"},\n",
    "    \"carbon_monoxide\":  {\"who\": 4.0,   \"epa\": 10.0,   \"unit\": \"mg/m³\"},  # 24-h mean\n",
    "}\n",
    "\n",
    "AQI_CATEGORIES = [\n",
    "    (0,   50,  \"Good\"),\n",
    "    (51,  100, \"Moderate\"),\n",
    "    (101, 150, \"Unhealthy for Sensitive Groups\"),\n",
    "    (151, 200, \"Unhealthy\"),\n",
    "    (201, 300, \"Very Unhealthy\"),\n",
    "    (301, 500, \"Hazardous\"),\n",
    "]\n",
    "\n",
    "OUTPUT_DIR = Path(\"output\")\n",
    "OUTPUT_DIR.mkdir(exist_ok=True)\n",
    "\n",
    "\n",
    "# ===========================================================================\n",
    "# DATABASE CONNECTION\n",
    "# ===========================================================================\n",
    "def get_db_engine():\n",
    "\n",
    "    host     = os.environ.get(\"DB_HOST\", \"localhost\")\n",
    "    port     = os.environ.get(\"DB_PORT\", \"5432\")\n",
    "    name     = os.environ.get(\"DB_NAME\", \"air_quality\")\n",
    "    user     = os.environ.get(\"DB_USER\", \"postgres\")\n",
    "    password = os.environ.get(\"DB_PASSWORD\")\n",
    "\n",
    "    if not password:\n",
    "        raise EnvironmentError(\n",
    "            \"DB_PASSWORD environment variable is not set. \"\n",
    "            \"Export it before running: export DB_PASSWORD=your_password\"\n",
    "        )\n",
    "\n",
    "    from sqlalchemy import create_engine\n",
    "    url = f\"postgresql+psycopg2://{user}:{password}@{host}:{port}/{name}\"\n",
    "    engine = create_engine(url, pool_pre_ping=True)\n",
    "    log.info(f\"  → PostgreSQL engine created: {user}@{host}:{port}/{name}\")\n",
    "    return engine\n",
    "\n",
    "\n",
    "# ===========================================================================\n",
    "# STEP 1 — EXTRACTION\n",
    "#pull data from API\n",
    "#Use 1 hr cache, validate list, create 2 data frames - readings and locations\n",
    "# ===========================================================================\n",
    "def extract_from_api() -> tuple[pd.DataFrame, pd.DataFrame]:\n",
    "\n",
    "    \n",
    "    log.info(\"Extracting data from Open-Meteo API …\")\n",
    "\n",
    " \n",
    "    try:\n",
    "        import openmeteo_requests\n",
    "        import requests_cache\n",
    "        from retry_requests import retry\n",
    "    except ImportError:\n",
    "        raise ImportError(\n",
    "            \"Install API dependencies: \"\n",
    "            \"pip install openmeteo-requests requests-cache retry-requests\"\n",
    "        )\n",
    "\n",
    "    cache_session = requests_cache.CachedSession(\".cache\", expire_after=3600)\n",
    "    retry_session = retry(cache_session, retries=5, backoff_factor=0.2)\n",
    "    openmeteo = openmeteo_requests.Client(session=retry_session)\n",
    "\n",
    "    try:\n",
    "        responses = openmeteo.weather_api(API_URL, params=API_PARAMS)\n",
    "    except Exception as e:\n",
    "        log.error(\"API request failed: %s\", e)\n",
    "        raise\n",
    "\n",
    "    expected = len(API_PARAMS[\"latitude\"])\n",
    "    if len(responses) != expected:\n",
    "        raise ValueError(\n",
    "            f\"API returned {len(responses)} responses; expected {expected}. \"\n",
    "            \"Check coordinates and API availability.\"\n",
    "        )\n",
    "    log.info(f\"  → {len(responses)} location responses received from API\")\n",
    "\n",
    "    readings_frames = []\n",
    "    location_rows = []\n",
    "\n",
    "    for idx, response in enumerate(responses):\n",
    "        meta = LOCATION_METADATA.get(idx, {})\n",
    "\n",
    "        location_rows.append({\n",
    "            \"location_id\":           idx,\n",
    "            \"name\":                  meta.get(\"name\", f\"Location {idx}\"),\n",
    "            \"state\":                 meta.get(\"state\"),\n",
    "            \"country\":               meta.get(\"country\", \"US\"),\n",
    "            \"latitude\":              response.Latitude(),\n",
    "            \"longitude\":             response.Longitude(),\n",
    "            \"elevation\":             response.Elevation(),\n",
    "            \"timezone\":              response.Timezone().decode(),\n",
    "            \"timezone_abbreviation\": response.TimezoneAbbreviation().decode(),\n",
    "            \"utc_offset_seconds\":    response.UtcOffsetSeconds(),\n",
    "        })\n",
    "\n",
    "        hourly = response.Hourly()\n",
    "        var_names = API_PARAMS[\"hourly\"]\n",
    "\n",
    "        # Build timestamp index for this location's hourly block\n",
    "        time_index = pd.date_range(\n",
    "            start=pd.to_datetime(hourly.Time(), unit=\"s\", utc=True),\n",
    "            end=pd.to_datetime(hourly.TimeEnd(), unit=\"s\", utc=True),\n",
    "            freq=pd.Timedelta(seconds=hourly.Interval()),\n",
    "            inclusive=\"left\",\n",
    "        )\n",
    "\n",
    "        if len(time_index) == 0:\n",
    "            log.warning(\"  [WARN] location_id=%d (%s) returned 0 hourly rows — skipping\",\n",
    "                        idx, meta.get(\"name\", \"unknown\"))\n",
    "            continue\n",
    "\n",
    "        data = {\"location_id\": idx, \"time\": time_index}\n",
    "        for i, name in enumerate(var_names):\n",
    "            data[name] = hourly.Variables(i).ValuesAsNumpy()\n",
    "\n",
    "        readings_frames.append(pd.DataFrame(data))\n",
    "\n",
    "    if not readings_frames:\n",
    "        raise RuntimeError(\"No hourly data was returned by the API for any location.\")\n",
    "\n",
    "    locations_df = pd.DataFrame(location_rows)\n",
    "    readings_df  = pd.concat(readings_frames, ignore_index=True)\n",
    "    log.info(f\"  → {len(readings_df):,} hourly rows across {len(locations_df)} locations\")\n",
    "    return readings_df, locations_df\n",
    "\n",
    "\n",
    "# ===========================================================================\n",
    "# STEP 2 — CLEANING & NORMALIZATION\n",
    "#1) parse timestamps, 2)remove impossible values (neg values), 3) interpole short gaps\n",
    "# ===========================================================================\n",
    "def clean_and_normalise(\n",
    "    readings_df: pd.DataFrame,\n",
    "    locations_df: pd.DataFrame,\n",
    ") -> tuple[pd.DataFrame, pd.DataFrame]:\n",
    "\n",
    "    log.info(\"Cleaning and normalising …\")\n",
    "\n",
    "    # --- Locations ---\n",
    "    loc = locations_df.copy()\n",
    "    loc[\"location_id\"] = loc[\"location_id\"].astype(int)\n",
    "    for col in [\"latitude\", \"longitude\", \"elevation\"]:\n",
    "        if col in loc.columns:\n",
    "            loc[col] = pd.to_numeric(loc[col], errors=\"coerce\")\n",
    "\n",
    "    # --- Readings ---\n",
    "    df = readings_df.copy()\n",
    "    df[\"location_id\"] = df[\"location_id\"].astype(int)\n",
    "\n",
    "    # Parse timestamps\n",
    "    df[\"time\"] = pd.to_datetime(df[\"time\"], utc=True, errors=\"coerce\")\n",
    "\n",
    "    numeric_cols = [c for c in df.columns if c not in (\"location_id\", \"time\")]\n",
    "    for col in numeric_cols:\n",
    "        df[col] = pd.to_numeric(df[col], errors=\"coerce\")\n",
    "\n",
    "    non_negative = [\n",
    "        \"pm10\", \"pm2_5\", \"carbon_monoxide\", \"carbon_dioxide\",\n",
    "        \"nitrogen_dioxide\", \"sulphur_dioxide\", \"ozone\", \"methane\",\n",
    "        \"uv_index\", \"uv_index_clear_sky\", \"dust\", \"aerosol_optical_depth\",\n",
    "        \"us_aqi\", \"us_aqi_pm2_5\", \"us_aqi_pm10\", \"us_aqi_nitrogen_dioxide\",\n",
    "        \"us_aqi_carbon_monoxide\", \"us_aqi_ozone\", \"us_aqi_sulphur_dioxide\",\n",
    "    ]\n",
    "    for col in non_negative:\n",
    "        if col in df.columns:\n",
    "            df[col] = df[col].clip(lower=0)\n",
    "\n",
    "    caps = {\"us_aqi\": 500, \"uv_index\": 20, \"aerosol_optical_depth\": 5}\n",
    "    for col, cap in caps.items():\n",
    "        if col in df.columns:\n",
    "            df[col] = df[col].clip(upper=cap)\n",
    "\n",
    "    measure_cols = [\n",
    "        \"pm10\", \"pm2_5\", \"carbon_monoxide\", \"carbon_dioxide\",\n",
    "        \"nitrogen_dioxide\", \"sulphur_dioxide\", \"ozone\", \"methane\",\n",
    "        \"uv_index\", \"dust\", \"aerosol_optical_depth\", \"us_aqi\",\n",
    "    ]\n",
    "    interp_frames = []\n",
    "    for _loc_id, grp in df.groupby(\"location_id\"):\n",
    "        grp = grp.sort_values(\"time\").copy()\n",
    "        for col in measure_cols:\n",
    "            if col in grp.columns:\n",
    "                grp[col] = grp[col].interpolate(method=\"linear\", limit=3)\n",
    "        interp_frames.append(grp)\n",
    "    df = pd.concat(interp_frames, ignore_index=True)\n",
    "\n",
    "    df = df.sort_values([\"location_id\", \"time\"]).reset_index(drop=True)\n",
    "    log.info(f\"  → {df.isnull().sum().sum():,} remaining nulls after interpolation\")\n",
    "    return df, loc\n",
    "\n",
    "\n",
    "# ===========================================================================\n",
    "# STEP 3 — TRANSFORMATION & DERIVED METRICS\n",
    "# - Add columns 1) AQI Cats (EPA AQI Cats), 2) Dom Poll - what is driving the AQI \n",
    "#3) PM Ratio - PM2.5/PM10 - Combustion or Dust (0-1) close to 0 | coarse = dust/pollen, close to 1 | fine = combustion\n",
    "#4) UV Cloud - % that UV is being surpressed by clouds, & 5)WHO Exceed - 0 within limit, 1 over\n",
    "#6) Date/hr/wk/day - time\n",
    "# ===========================================================================\n",
    "def _aqi_category(val):\n",
    "    \"\"\"Map a numeric AQI value to its EPA category label.\"\"\"\n",
    "    if pd.isna(val):\n",
    "        return None\n",
    "    for lo, hi, label in AQI_CATEGORIES:\n",
    "        if lo <= val <= hi:\n",
    "            return label\n",
    "    return \"Hazardous\"\n",
    "\n",
    "def transform(df: pd.DataFrame) -> pd.DataFrame:\n",
    "\n",
    "    log.info(\"Transforming and deriving metrics …\")\n",
    "    df = df.copy()\n",
    "\n",
    "    df[\"aqi_category\"] = df[\"us_aqi\"].map(_aqi_category)\n",
    "\n",
    "    sub_aqi_cols = {\n",
    "        \"us_aqi_pm2_5\":            \"PM2.5\",\n",
    "        \"us_aqi_pm10\":             \"PM10\",\n",
    "        \"us_aqi_ozone\":            \"Ozone\",\n",
    "        \"us_aqi_nitrogen_dioxide\": \"NO₂\",\n",
    "        \"us_aqi_carbon_monoxide\":  \"CO\",\n",
    "        \"us_aqi_sulphur_dioxide\":  \"SO₂\",\n",
    "    }\n",
    "    present = [c for c in sub_aqi_cols if c in df.columns]\n",
    "    if present:\n",
    "        sub     = df[present].copy().astype(float)\n",
    "        all_na  = sub.isna().all(axis=1)\n",
    "        dominant = pd.Series(index=df.index, dtype=object)\n",
    "        if (~all_na).any():\n",
    "            dominant[~all_na] = (\n",
    "                sub[~all_na].idxmax(axis=1, skipna=True).map(sub_aqi_cols)\n",
    "            )\n",
    "        df[\"dominant_pollutant\"] = dominant\n",
    "\n",
    "    df[\"pm_ratio\"] = (df[\"pm2_5\"] / df[\"pm10\"].replace(0, np.nan)).round(3)\n",
    "\n",
    "    df[\"uv_cloud_attenuation_pct\"] = np.where(\n",
    "        df[\"uv_index_clear_sky\"] > 0,\n",
    "        ((df[\"uv_index_clear_sky\"] - df[\"uv_index\"])\n",
    "         / df[\"uv_index_clear_sky\"] * 100).round(1),\n",
    "        np.nan,\n",
    "    )\n",
    "\n",
    "    who_map = {\n",
    "        \"pm2_5\":            THRESHOLDS[\"pm2_5\"][\"who\"],\n",
    "        \"pm10\":             THRESHOLDS[\"pm10\"][\"who\"],\n",
    "        \"ozone\":            THRESHOLDS[\"ozone\"][\"who\"],\n",
    "        \"nitrogen_dioxide\": THRESHOLDS[\"nitrogen_dioxide\"][\"who\"],\n",
    "        \"sulphur_dioxide\":  THRESHOLDS[\"sulphur_dioxide\"][\"who\"],\n",
    "    }\n",
    "    for col, limit in who_map.items():\n",
    "        if col in df.columns:\n",
    "            df[f\"who_exceedance_{col}\"] = (df[col] > limit).astype(\"Int8\")\n",
    "\n",
    "    df[\"date\"]        = df[\"time\"].dt.date\n",
    "    df[\"hour\"]        = df[\"time\"].dt.hour\n",
    "    df[\"week\"]        = df[\"time\"].dt.isocalendar().week.astype(int)\n",
    "    df[\"day_of_week\"] = df[\"time\"].dt.day_name()\n",
    "\n",
    "    log.info(\"  → Derived columns added\")\n",
    "    return df\n",
    "\n",
    "\n",
    "# ===========================================================================\n",
    "# STEP 4 — DATA VALIDATION & QUALITY CHECKS\n",
    "# ===========================================================================\n",
    "def validate(df: pd.DataFrame, locations_df: pd.DataFrame) -> pd.DataFrame:\n",
    "\n",
    "    log.info(\"Running data validation …\")\n",
    "    issues = []\n",
    "\n",
    "    def flag(check, col, count, detail=\"\"):\n",
    "        level = \"PASS\" if count == 0 else \"FAIL\"\n",
    "        if count:\n",
    "            log.warning(\"  [QA %s] %s | column: %s | %s rows | %s\",\n",
    "                        level, check, col, f\"{count:,}\", detail)\n",
    "        else:\n",
    "            log.info(\"  [QA %s] %s\", level, check)\n",
    "        issues.append({\n",
    "            \"check\": check, \"column\": col,\n",
    "            \"failed_rows\": count, \"detail\": detail, \"status\": level,\n",
    "        })\n",
    "\n",
    "    # 1. Null timestamps\n",
    "    flag(\"null_time\", \"time\", int(df[\"time\"].isna().sum()))\n",
    "\n",
    "    # 2. Duplicate (location_id, time) pairs\n",
    "    dups = int(df.duplicated(subset=[\"location_id\", \"time\"]).sum())\n",
    "    flag(\"duplicate_location_time\", \"location_id+time\", dups)\n",
    "\n",
    "    # 3. Referential integrity — readings must reference known locations\n",
    "    valid_ids = set(locations_df[\"location_id\"].unique())\n",
    "    unknown = int((~df[\"location_id\"].isin(valid_ids)).sum())\n",
    "    flag(\"unknown_location_id\", \"location_id\", unknown)\n",
    "\n",
    "    # 4. AQI range (EPA scale: 0–500)\n",
    "    if \"us_aqi\" in df.columns:\n",
    "        oob = df[\"us_aqi\"].between(0, 500, inclusive=\"both\")\n",
    "        flag(\"aqi_out_of_range\", \"us_aqi\",\n",
    "             int((~oob & df[\"us_aqi\"].notna()).sum()), \"valid range 0–500\")\n",
    "\n",
    "    # 5. UV index range (0–20; values above 11 are Extreme)\n",
    "    if \"uv_index\" in df.columns:\n",
    "        oob = df[\"uv_index\"].between(0, 20, inclusive=\"both\")\n",
    "        flag(\"uv_out_of_range\", \"uv_index\",\n",
    "             int((~oob & df[\"uv_index\"].notna()).sum()), \"valid range 0–20\")\n",
    "\n",
    "    # 6. Negative concentrations — should be zero after clipping step\n",
    "    for col in [\"pm2_5\", \"pm10\", \"ozone\", \"carbon_monoxide\"]:\n",
    "        if col in df.columns:\n",
    "            neg = int((df[col] < 0).sum())\n",
    "            flag(\"negative_concentration\", col, neg)\n",
    "\n",
    "    # 7. High null rate per column (threshold: > 20%)\n",
    "    total = len(df)\n",
    "    for col in df.columns:\n",
    "        miss = int(df[col].isna().sum())\n",
    "        if miss / total > 0.20:\n",
    "            flag(\"high_null_rate\", col, miss, f\"{miss / total:.1%} missing\")\n",
    "\n",
    "    # 8. Temporal gaps > 1 hour within each location's time series\n",
    "    for loc_id, grp in df.groupby(\"location_id\"):\n",
    "        grp  = grp.sort_values(\"time\")\n",
    "        gaps = grp[\"time\"].diff().dt.total_seconds() / 3600\n",
    "        large = int((gaps > 1).sum())\n",
    "        if large:\n",
    "            flag(\"temporal_gap\", \"time\", large,\n",
    "                 f\"location_id={loc_id} has {large} gap(s) > 1 h\")\n",
    "\n",
    "    # 9. Row count verification — confirm expected rows per location\n",
    "    expected_rows_per_loc = 7 * 24  # 7-day forecast at hourly resolution\n",
    "    for loc_id, grp in df.groupby(\"location_id\"):\n",
    "        actual = len(grp)\n",
    "        if actual < expected_rows_per_loc:\n",
    "            flag(\"low_row_count\", \"location_id\",\n",
    "                 expected_rows_per_loc - actual,\n",
    "                 f\"location_id={loc_id}: got {actual}, expected {expected_rows_per_loc}\")\n",
    "\n",
    "    qa_df  = pd.DataFrame(issues)\n",
    "    passed = int((qa_df[\"failed_rows\"] == 0).sum())\n",
    "    failed = int((qa_df[\"failed_rows\"] > 0).sum())\n",
    "    log.info(\"  → QA complete: %d checks passed, %d with issues\", passed, failed)\n",
    "    return qa_df\n",
    "\n",
    "\n",
    "# ===========================================================================\n",
    "# STEP 5 — DATABASE LOADING (PostgreSQL) & CSV EXPORT\n",
    "    #Create hub and spoke table to postgreSQL - INCREMENTAL LOADING STARAGEGY IS THIS:\n",
    "    #Open-Meteo API returns a rolling 7-day forcast \n",
    "    #Each run will overlap with the previous and a full replace will lose any manual annotations \n",
    "\n",
    "    #Rec strategy - Append with Deduplication\n",
    "    #1 - load full incoming dataframe into temp staging table\n",
    "    #2 - delete from permanent table any rows whose loc_ID, time already exist\n",
    "    #3 insert all rows from staging into perm table\n",
    "\n",
    "    #Allows for no duplications over time, updated forcast values, and rows not present in new window remain untouched\n",
    "    #Audit table is also maintained \n",
    "# ===========================================================================\n",
    "def load_to_postgres(\n",
    "    df: pd.DataFrame,\n",
    "    locations_df: pd.DataFrame,\n",
    "    engine,\n",
    ") -> None:\n",
    "   \n",
    "    from sqlalchemy import text\n",
    "\n",
    "    log.info(\"Loading to PostgreSQL (incremental append with deduplication) …\")\n",
    "\n",
    "    run_started_at = datetime.now(timezone.utc)\n",
    "    rows_in = len(df)\n",
    "\n",
    "    try:\n",
    "        # ------------------------------------------------------------------\n",
    "        # Locations — upsert: insert new, update existing on conflict\n",
    "        # ------------------------------------------------------------------\n",
    "        with engine.begin() as conn:\n",
    "            conn.execute(text(\"\"\"\n",
    "                CREATE TABLE IF NOT EXISTS locations (\n",
    "                    location_id          INTEGER PRIMARY KEY,\n",
    "                    name                 TEXT,\n",
    "                    state                TEXT,\n",
    "                    country              TEXT,\n",
    "                    latitude             DOUBLE PRECISION,\n",
    "                    longitude            DOUBLE PRECISION,\n",
    "                    elevation            DOUBLE PRECISION,\n",
    "                    timezone             TEXT,\n",
    "                    timezone_abbreviation TEXT,\n",
    "                    utc_offset_seconds   INTEGER\n",
    "                )\n",
    "            \"\"\"))\n",
    "\n",
    "        # Stage locations then upsert\n",
    "        locations_df.to_sql(\"locations_stage\", engine,\n",
    "                            if_exists=\"replace\", index=False)\n",
    "        with engine.begin() as conn:\n",
    "            conn.execute(text(\"\"\"\n",
    "                INSERT INTO locations\n",
    "                SELECT * FROM locations_stage\n",
    "                ON CONFLICT (location_id) DO UPDATE SET\n",
    "                    name                  = EXCLUDED.name,\n",
    "                    latitude              = EXCLUDED.latitude,\n",
    "                    longitude             = EXCLUDED.longitude,\n",
    "                    elevation             = EXCLUDED.elevation,\n",
    "                    timezone              = EXCLUDED.timezone,\n",
    "                    timezone_abbreviation = EXCLUDED.timezone_abbreviation,\n",
    "                    utc_offset_seconds    = EXCLUDED.utc_offset_seconds\n",
    "            \"\"\"))\n",
    "            conn.execute(text(\"DROP TABLE IF EXISTS locations_stage\"))\n",
    "        log.info(\"  → locations: upserted %d rows\", len(locations_df))\n",
    "\n",
    "        # ------------------------------------------------------------------\n",
    "        # Build the readings hub with reading_id assigned from df index\n",
    "        # ------------------------------------------------------------------\n",
    "        df = df.copy()\n",
    "        df[\"reading_id\"]  = df.index\n",
    "        df[\"data_source\"] = \"api\"\n",
    "        df[\"created_at\"]  = run_started_at\n",
    "\n",
    "        # Helper: incremental load for a given spoke table\n",
    "        def incremental_load(table: str, cols: list[str]) -> int:\n",
    "            \"\"\"\n",
    "            Stage → delete matching keys → insert.\n",
    "            Returns the number of rows written.\n",
    "            \"\"\"\n",
    "            subset = df[[c for c in cols if c in df.columns]].copy()\n",
    "            if subset.empty:\n",
    "                return 0\n",
    "\n",
    "            stage = f\"{table}_stage\"\n",
    "            subset.to_sql(stage, engine, if_exists=\"replace\", index=False)\n",
    "\n",
    "            key_cols = [\"location_id\", \"time\"] if \"time\" in cols else [\"reading_id\"]\n",
    "            key_join = \" AND \".join(\n",
    "                f\"{table}.{k} = {stage}.{k}\" for k in key_cols\n",
    "            )\n",
    "            with engine.begin() as conn:\n",
    "                conn.execute(text(f\"\"\"\n",
    "                    CREATE TABLE IF NOT EXISTS {table}\n",
    "                    AS SELECT * FROM {stage} WHERE 1=0\n",
    "                \"\"\"))\n",
    "                conn.execute(text(f\"\"\"\n",
    "                    DELETE FROM {table}\n",
    "                    USING {stage}\n",
    "                    WHERE {key_join}\n",
    "                \"\"\"))\n",
    "                conn.execute(text(f\"INSERT INTO {table} SELECT * FROM {stage}\"))\n",
    "                conn.execute(text(f\"DROP TABLE IF EXISTS {stage}\"))\n",
    "\n",
    "            log.info(\"  → %s: %d rows written\", table, len(subset))\n",
    "            return len(subset)\n",
    "\n",
    "        # ------------------------------------------------------------------\n",
    "        # Readings hub\n",
    "        # ------------------------------------------------------------------\n",
    "        hub_cols = [\"reading_id\", \"location_id\", \"time\", \"data_source\", \"created_at\"]\n",
    "        incremental_load(\"readings\", hub_cols)\n",
    "\n",
    "        # ------------------------------------------------------------------\n",
    "        # Spoke tables (one per variable group)\n",
    "        # ------------------------------------------------------------------\n",
    "        incremental_load(\"particulates\", [\n",
    "            \"reading_id\", \"pm10\", \"pm2_5\", \"us_aqi\", \"aqi_category\",\n",
    "        ])\n",
    "        incremental_load(\"gaseous_pollutants\", [\n",
    "            \"reading_id\", \"carbon_monoxide\", \"nitrogen_dioxide\",\n",
    "            \"sulphur_dioxide\", \"ozone\",\n",
    "        ])\n",
    "        incremental_load(\"greenhouse_gases\", [\n",
    "            \"reading_id\", \"carbon_dioxide\", \"methane\",\n",
    "        ])\n",
    "        incremental_load(\"atmospheric\", [\n",
    "            \"reading_id\", \"uv_index\", \"uv_index_clear_sky\",\n",
    "            \"aerosol_optical_depth\", \"dust\",\n",
    "        ])\n",
    "\n",
    "        # ------------------------------------------------------------------\n",
    "        # Row count verification — confirm DB row count matches input\n",
    "        # ------------------------------------------------------------------\n",
    "        with engine.connect() as conn:\n",
    "            db_count = conn.execute(\n",
    "                text(\"SELECT COUNT(*) FROM readings WHERE data_source = 'api'\")\n",
    "            ).scalar()\n",
    "        log.info(\"  → Row count check: %d rows in DB readings table\", db_count)\n",
    "\n",
    "        # ------------------------------------------------------------------\n",
    "        # Audit log — record this pipeline run\n",
    "        # ------------------------------------------------------------------\n",
    "        with engine.begin() as conn:\n",
    "            conn.execute(text(\"\"\"\n",
    "                CREATE TABLE IF NOT EXISTS pipeline_runs (\n",
    "                    run_id          SERIAL PRIMARY KEY,\n",
    "                    started_at      TIMESTAMPTZ,\n",
    "                    completed_at    TIMESTAMPTZ,\n",
    "                    rows_extracted  INTEGER,\n",
    "                    db_row_count    INTEGER,\n",
    "                    status          TEXT\n",
    "                )\n",
    "            \"\"\"))\n",
    "            conn.execute(text(\"\"\"\n",
    "                INSERT INTO pipeline_runs\n",
    "                    (started_at, completed_at, rows_extracted, db_row_count, status)\n",
    "                VALUES\n",
    "                    (:started, :completed, :extracted, :db_count, 'SUCCESS')\n",
    "            \"\"\"), {\n",
    "                \"started\":   run_started_at,\n",
    "                \"completed\": datetime.now(timezone.utc),\n",
    "                \"extracted\": rows_in,\n",
    "                \"db_count\":  db_count,\n",
    "            })\n",
    "        log.info(\"  → Pipeline run recorded in pipeline_runs audit table\")\n",
    "\n",
    "    except Exception as e:\n",
    "        log.error(\"Database load failed: %s\", e)\n",
    "        # Record the failed run in the audit table if possible\n",
    "        try:\n",
    "            with engine.begin() as conn:\n",
    "                conn.execute(text(\"\"\"\n",
    "                    CREATE TABLE IF NOT EXISTS pipeline_runs (\n",
    "                        run_id SERIAL PRIMARY KEY, started_at TIMESTAMPTZ,\n",
    "                        completed_at TIMESTAMPTZ, rows_extracted INTEGER,\n",
    "                        db_row_count INTEGER, status TEXT\n",
    "                    )\n",
    "                \"\"\"))\n",
    "                conn.execute(text(\"\"\"\n",
    "                    INSERT INTO pipeline_runs\n",
    "                        (started_at, completed_at, rows_extracted, db_row_count, status)\n",
    "                    VALUES (:started, :completed, :extracted, NULL, 'FAILED')\n",
    "                \"\"\"), {\n",
    "                    \"started\":   run_started_at,\n",
    "                    \"completed\": datetime.now(timezone.utc),\n",
    "                    \"extracted\": rows_in,\n",
    "                })\n",
    "        except Exception as audit_err:\n",
    "            log.warning(\"Could not write failure record to pipeline_runs: %s\", audit_err)\n",
    "        raise\n",
    "\n",
    "\n",
    "def export_csvs(df: pd.DataFrame, locations_df: pd.DataFrame, qa_df: pd.DataFrame) -> None:\n",
    "    \"\"\"Write cleaned/enriched flat files for local inspection and backup.\"\"\"\n",
    "    log.info(\"Exporting CSVs to %s …\", OUTPUT_DIR)\n",
    "    try:\n",
    "        locations_df.to_csv(OUTPUT_DIR / \"locations.csv\", index=False)\n",
    "        df.to_csv(OUTPUT_DIR / \"readings_clean.csv\", index=False)\n",
    "        qa_df.to_csv(OUTPUT_DIR / \"qa_report.csv\", index=False)\n",
    "        log.info(\"  → CSVs written: locations.csv, readings_clean.csv, qa_report.csv\")\n",
    "    except OSError as e:\n",
    "        log.error(\"CSV export failed: %s\", e)\n",
    "        raise\n",
    "\n",
    "\n",
    "# ===========================================================================\n",
    "# STEP 6 — ANALYTICS-READY DATASETS\n",
    "    #Produce 3 files - \n",
    "    #1) Analytics Daily Summary - 1 row per location x date with mena and max per variable\n",
    "        #can load into Power Bi or Dash\n",
    "    #2) Analytics AQI Wide \n",
    "        #Pivoted Wide for timeseries analysis - 1 column per city indexed by time \n",
    "    #3) Analytics who exceedances\n",
    "        #Only rows where at least one guideline is breached \n",
    "        #ALERTS, COMPLIANCE, OR CREATE A EXCEEDANCE MAP!\n",
    "# ===========================================================================\n",
    "def build_analytics_datasets(df: pd.DataFrame, locations_df: pd.DataFrame) -> None:\n",
    "\n",
    "    log.info(\"Building analytics-ready datasets …\")\n",
    "\n",
    "    try:\n",
    "        loc_name = locations_df.set_index(\"location_id\")[\"name\"].to_dict()\n",
    "        df = df.copy()\n",
    "        df[\"city\"] = df[\"location_id\"].map(loc_name)\n",
    "\n",
    "        # ------------------------------------------------------------------\n",
    "        # A) Daily summary\n",
    "        # ------------------------------------------------------------------\n",
    "        agg_map = {\n",
    "            \"pm2_5\":                  [\"mean\", \"max\"],\n",
    "            \"pm10\":                   [\"mean\", \"max\"],\n",
    "            \"ozone\":                  [\"mean\", \"max\"],\n",
    "            \"nitrogen_dioxide\":       [\"mean\", \"max\"],\n",
    "            \"sulphur_dioxide\":        [\"mean\", \"max\"],\n",
    "            \"carbon_monoxide\":        [\"mean\", \"max\"],\n",
    "            \"carbon_dioxide\":         [\"mean\"],\n",
    "            \"methane\":                [\"mean\"],\n",
    "            \"us_aqi\":                 [\"mean\", \"max\"],\n",
    "            \"uv_index\":               [\"max\"],\n",
    "            \"aerosol_optical_depth\":  [\"mean\"],\n",
    "            \"dust\":                   [\"mean\", \"max\"],\n",
    "            \"pm_ratio\":               [\"mean\"],\n",
    "            \"uv_cloud_attenuation_pct\": [\"mean\"],\n",
    "        }\n",
    "        agg_map = {k: v for k, v in agg_map.items() if k in df.columns}\n",
    "\n",
    "        daily = (\n",
    "            df.groupby([\"location_id\", \"city\", \"date\"])\n",
    "            .agg(agg_map)\n",
    "            .reset_index()\n",
    "        )\n",
    "        daily.columns = [\n",
    "            \"_\".join(c).strip(\"_\") if isinstance(c, tuple) else c\n",
    "            for c in daily.columns\n",
    "        ]\n",
    "\n",
    "        if \"dominant_pollutant\" in df.columns:\n",
    "            dominant = (\n",
    "                df.groupby([\"location_id\", \"date\"])[\"dominant_pollutant\"]\n",
    "                .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)\n",
    "                .reset_index()\n",
    "            )\n",
    "            daily = daily.merge(dominant, on=[\"location_id\", \"date\"], how=\"left\")\n",
    "\n",
    "        if \"aqi_category\" in df.columns:\n",
    "            cat = (\n",
    "                df.groupby([\"location_id\", \"date\"])[\"aqi_category\"]\n",
    "                .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else None)\n",
    "                .reset_index()\n",
    "                .rename(columns={\"aqi_category\": \"dominant_aqi_category\"})\n",
    "            )\n",
    "            daily = daily.merge(cat, on=[\"location_id\", \"date\"], how=\"left\")\n",
    "\n",
    "        daily.to_csv(OUTPUT_DIR / \"analytics_daily_summary.csv\", index=False)\n",
    "        log.info(\"  A) Daily summary: %d rows → analytics_daily_summary.csv\", len(daily))\n",
    "\n",
    "        # ------------------------------------------------------------------\n",
    "        # B) AQI wide pivot\n",
    "        # ------------------------------------------------------------------\n",
    "        if \"us_aqi\" in df.columns:\n",
    "            wide = df.pivot_table(\n",
    "                index=\"time\", columns=\"city\", values=\"us_aqi\", aggfunc=\"mean\"\n",
    "            ).reset_index()\n",
    "            wide.to_csv(OUTPUT_DIR / \"analytics_aqi_wide.csv\", index=False)\n",
    "            log.info(\"  B) AQI wide pivot: %s → analytics_aqi_wide.csv\", wide.shape)\n",
    "\n",
    "        # ------------------------------------------------------------------\n",
    "        # C) WHO exceedance log\n",
    "        # ------------------------------------------------------------------\n",
    "        exc_cols = [c for c in df.columns if c.startswith(\"who_exceedance_\")]\n",
    "        if exc_cols:\n",
    "            any_exceedance = df[exc_cols].eq(1).any(axis=1)\n",
    "            exc_df = df[any_exceedance].copy()\n",
    "            exc_df.to_csv(OUTPUT_DIR / \"analytics_who_exceedances.csv\", index=False)\n",
    "            log.info(\"  C) WHO exceedance log: %d rows → analytics_who_exceedances.csv\",\n",
    "                     len(exc_df))\n",
    "\n",
    "        log.info(\"Analytics datasets ready.\")\n",
    "\n",
    "    except Exception as e:\n",
    "        log.error(\"Analytics dataset build failed: %s\", e)\n",
    "        raise\n",
    "\n",
    "\n",
    "# ===========================================================================\n",
    "# MAIN — orchestrate all steps\n",
    "# ===========================================================================\n",
    "def run_pipeline() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:\n",
    "    \"\"\"\n",
    "    Orchestrate the full ETL pipeline:\n",
    "      1. Extract  — fetch live data from Open-Meteo API\n",
    "      2. Clean    — normalise types, clip outliers, interpolate short gaps\n",
    "      3. Transform— add derived metrics and time features\n",
    "      4. Validate — run QA checks and log results\n",
    "      5. Load     — incremental upsert to PostgreSQL + CSV backup\n",
    "      6. Analytics— build summary datasets for Power BI / Plotly Dash\n",
    "\n",
    "    Returns (enriched_df, locations_df, qa_df) for interactive use.\n",
    "    Raises on any unrecoverable error after logging a clear message.\n",
    "    \"\"\"\n",
    "    log.info(\"=\" * 60)\n",
    "    log.info(\"Air Quality Pipeline — START\")\n",
    "    log.info(\"=\" * 60)\n",
    "\n",
    "    try:\n",
    "        # 1. Extract\n",
    "        raw_df, locations_df = extract_from_api()\n",
    "\n",
    "        # 2. Clean\n",
    "        clean_df, locations_df = clean_and_normalise(raw_df, locations_df)\n",
    "\n",
    "        # 3. Transform\n",
    "        enriched_df = transform(clean_df)\n",
    "\n",
    "        # 4. Validate\n",
    "        qa_df = validate(enriched_df, locations_df)\n",
    "\n",
    "        # 5. Load — build engine once and share across load + audit steps\n",
    "        engine = get_db_engine()\n",
    "        load_to_postgres(enriched_df, locations_df, engine)\n",
    "        export_csvs(enriched_df, locations_df, qa_df)\n",
    "\n",
    "        # 6. Analytics datasets\n",
    "        build_analytics_datasets(enriched_df, locations_df)\n",
    "\n",
    "    except Exception as e:\n",
    "        log.error(\"Pipeline failed: %s\", e)\n",
    "        raise\n",
    "\n",
    "    log.info(\"=\" * 60)\n",
    "    log.info(\"Pipeline complete.\")\n",
    "    log.info(\"=\" * 60)\n",
    "    return enriched_df, locations_df, qa_df\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "if __name__ == \"__main__\":\n",
    "    enriched_df, locations_df, qa_df = run_pipeline()\n",
    "\n",
    "    print(\"\\nSample enriched data:\")\n",
    "    print(enriched_df[\n",
    "        [\"location_id\", \"time\", \"us_aqi\", \"aqi_category\", \"dominant_pollutant\", \"pm_ratio\"]\n",
    "    ].head(10).to_string(index=False))\n",
    "\n",
    "    print(\"\\nQA Report:\")\n",
    "    print(qa_df.to_string(index=False))\n"
   ]
  },
  {
   "cell_type": "raw",
   "id": "d201e889-35b6-45bf-a691-9e188520a76d",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
